// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package task

import (
	"github.com/mijjjj/gcoll/api/task"
	runtimesvc "github.com/mijjjj/gcoll/internal/service/runtime"
)

type ControllerV1 struct {
	runtimeSvc *runtimesvc.Service
}

func NewV1() task.ITaskV1 {
	return &ControllerV1{
		runtimeSvc: runtimesvc.New(),
	}
}
