// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// collectionTasksDao is the data access object for the table collection_tasks.
// You can define custom methods on it to extend its functionality as needed.
type collectionTasksDao struct {
	*internal.CollectionTasksDao
}

var (
	// CollectionTasks is a globally accessible object for table collection_tasks operations.
	CollectionTasks = collectionTasksDao{internal.NewCollectionTasksDao()}
)

// Add your custom methods and functionality below.
