// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// deviceGroupsDao is the data access object for the table device_groups.
// You can define custom methods on it to extend its functionality as needed.
type deviceGroupsDao struct {
	*internal.DeviceGroupsDao
}

var (
	// DeviceGroups is a globally accessible object for table device_groups operations.
	DeviceGroups = deviceGroupsDao{internal.NewDeviceGroupsDao()}
)

// Add your custom methods and functionality below.
