// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// devicePointVersionsDao is the data access object for the table device_point_versions.
// You can define custom methods on it to extend its functionality as needed.
type devicePointVersionsDao struct {
	*internal.DevicePointVersionsDao
}

var (
	// DevicePointVersions is a globally accessible object for table device_point_versions operations.
	DevicePointVersions = devicePointVersionsDao{internal.NewDevicePointVersionsDao()}
)

// Add your custom methods and functionality below.
