// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// devicesDao is the data access object for the table devices.
// You can define custom methods on it to extend its functionality as needed.
type devicesDao struct {
	*internal.DevicesDao
}

var (
	// Devices is a globally accessible object for table devices operations.
	Devices = devicesDao{internal.NewDevicesDao()}
)

// Add your custom methods and functionality below.
