// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// devicePointsDao is the data access object for the table device_points.
// You can define custom methods on it to extend its functionality as needed.
type devicePointsDao struct {
	*internal.DevicePointsDao
}

var (
	// DevicePoints is a globally accessible object for table device_points operations.
	DevicePoints = devicePointsDao{internal.NewDevicePointsDao()}
)

// Add your custom methods and functionality below.
