// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// modbusTcpDebugLogsDao is the data access object for the table modbus_tcp_debug_logs.
// You can define custom methods on it to extend its functionality as needed.
type modbusTcpDebugLogsDao struct {
	*internal.ModbusTcpDebugLogsDao
}

var (
	// ModbusTcpDebugLogs is a globally accessible object for table modbus_tcp_debug_logs operations.
	ModbusTcpDebugLogs = modbusTcpDebugLogsDao{internal.NewModbusTcpDebugLogsDao()}
)

// Add your custom methods and functionality below.
