// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// modbusTcpPointProfilesDao is the data access object for the table modbus_tcp_point_profiles.
// You can define custom methods on it to extend its functionality as needed.
type modbusTcpPointProfilesDao struct {
	*internal.ModbusTcpPointProfilesDao
}

var (
	// ModbusTcpPointProfiles is a globally accessible object for table modbus_tcp_point_profiles operations.
	ModbusTcpPointProfiles = modbusTcpPointProfilesDao{internal.NewModbusTcpPointProfilesDao()}
)

// Add your custom methods and functionality below.
