// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// modbusTcpDeviceProfilesDao is the data access object for the table modbus_tcp_device_profiles.
// You can define custom methods on it to extend its functionality as needed.
type modbusTcpDeviceProfilesDao struct {
	*internal.ModbusTcpDeviceProfilesDao
}

var (
	// ModbusTcpDeviceProfiles is a globally accessible object for table modbus_tcp_device_profiles operations.
	ModbusTcpDeviceProfiles = modbusTcpDeviceProfilesDao{internal.NewModbusTcpDeviceProfilesDao()}
)

// Add your custom methods and functionality below.
