// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// pluginVersionsDao is the data access object for the table plugin_versions.
// You can define custom methods on it to extend its functionality as needed.
type pluginVersionsDao struct {
	*internal.PluginVersionsDao
}

var (
	// PluginVersions is a globally accessible object for table plugin_versions operations.
	PluginVersions = pluginVersionsDao{internal.NewPluginVersionsDao()}
)

// Add your custom methods and functionality below.
