// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// pluginDeviceConfigVersionsDao is the data access object for the table plugin_device_config_versions.
// You can define custom methods on it to extend its functionality as needed.
type pluginDeviceConfigVersionsDao struct {
	*internal.PluginDeviceConfigVersionsDao
}

var (
	// PluginDeviceConfigVersions is a globally accessible object for table plugin_device_config_versions operations.
	PluginDeviceConfigVersions = pluginDeviceConfigVersionsDao{internal.NewPluginDeviceConfigVersionsDao()}
)

// Add your custom methods and functionality below.
