// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// pluginConfigSchemasDao is the data access object for the table plugin_config_schemas.
// You can define custom methods on it to extend its functionality as needed.
type pluginConfigSchemasDao struct {
	*internal.PluginConfigSchemasDao
}

var (
	// PluginConfigSchemas is a globally accessible object for table plugin_config_schemas operations.
	PluginConfigSchemas = pluginConfigSchemasDao{internal.NewPluginConfigSchemasDao()}
)

// Add your custom methods and functionality below.
