// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// pluginsDao is the data access object for the table plugins.
// You can define custom methods on it to extend its functionality as needed.
type pluginsDao struct {
	*internal.PluginsDao
}

var (
	// Plugins is a globally accessible object for table plugins operations.
	Plugins = pluginsDao{internal.NewPluginsDao()}
)

// Add your custom methods and functionality below.
