// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// pluginDeviceConfigsDao is the data access object for the table plugin_device_configs.
// You can define custom methods on it to extend its functionality as needed.
type pluginDeviceConfigsDao struct {
	*internal.PluginDeviceConfigsDao
}

var (
	// PluginDeviceConfigs is a globally accessible object for table plugin_device_configs operations.
	PluginDeviceConfigs = pluginDeviceConfigsDao{internal.NewPluginDeviceConfigsDao()}
)

// Add your custom methods and functionality below.
