// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/mijjjj/gcoll/internal/dao/internal"
)

// runtimeEventsDao is the data access object for the table runtime_events.
// You can define custom methods on it to extend its functionality as needed.
type runtimeEventsDao struct {
	*internal.RuntimeEventsDao
}

var (
	// RuntimeEvents is a globally accessible object for table runtime_events operations.
	RuntimeEvents = runtimeEventsDao{internal.NewRuntimeEventsDao()}
)

// Add your custom methods and functionality below.
